packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalog:
  '@shikijs/vitepress-twoslash': ^3.2.1
  '@types/fs-extra': ^11.0.4
  '@types/markdown-it-container': ^2.0.10
  '@vue/compiler-core': ^3.5.13
  '@vue/compiler-sfc': ^3.5.13
  esbuild: ^0.25.1
  fs-extra: ^11.3.0
  markdown-it-container: ^4.0.0
  oxc-transform: ^0.61.1
  vitepress: ^1.6.3
  vue: ^3.5.13
catalogs:
  cli:
    '@antfu/eslint-config': ^4.10.1
    '@antfu/ni': ^24.1.0
    bumpp: ^10.1.0
    eslint: ^9.22.0
    lint-staged: ^15.5.0
    simple-git-hooks: ^2.11.1
    tsup: ^8.4.0
    tsx: ^4.19.3
    typescript: ^5.8.2
    vite: ^6.2.1
  inlined:
    '@antfu/utils': ^9.1.0
  testing:
    vitest: ^3.0.8
    vitest-package-exports: ^0.1.1
    yaml: ^2.7.0
  types:
    '@types/node': ^22.13.10
  utils:
    tinyexec: ^0.3.2
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
